apiVersion: v1
kind: Service
metadata:
  name: cloud-gateway
spec:
  selector:
    app: cloud-gateway
  ports:
    - protocol: TCP
      port: 8091
      targetPort: 8091

---
apiVersion: v1
kind: Service
metadata:
  name: membership
spec:
  selector:
    app: membership
  ports:
    - protocol: TCP
      port: 8089
      targetPort: 8089

---
apiVersion: v1
kind: Service
metadata:
  name: payment
spec:
  selector:
    app: payment
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090

---
apiVersion: v1
kind: Service
metadata:
  name: members
spec:
  selector:
    app: members
  ports:
    - protocol: TCP
      port: 8092
      targetPort: 8092

---
apiVersion: v1
kind: Service
metadata:
  name: member-class
spec:
  selector:
    app: member-class
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 8088

---
apiVersion: v1
kind: Service
metadata:
  name: service-registry
spec:
  selector:
    app: service-registry
  ports:
    - protocol: TCP
      port: 8761
      targetPort: 8761

---
apiVersion: v1
kind: Service
metadata:
  name: zipkin
spec:
  selector:
    app: zipkin
  ports:
    - protocol: TCP
      port: 9411
      targetPort: 9411
