spring:
  zipkin:
    base-url: http://localhost:9411/
  application:
    name: members

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb

server:
  port: 8092
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
